# Generated by Django 5.2.7 on 2025-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('general', 'General'), ('ticket_creado', 'Ticket Creado'), ('ticket_asignado', 'Ticket Asignado'), ('ticket_nuevo_admin', 'Nuevo Ticket (Admin)'), ('ticket_actualizado', 'Ticket Actualizado'), ('ticket_cerrado', 'Ticket Cerrado'), ('ticket_eliminado', 'Ticket Eliminado'), ('ticket_reasignado', 'Ticket Reasignado'), ('sistema', 'Sistema')], default='general', max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
