# Generated by Django 5.2.7 on 2025-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('ticket_creado', 'Ticket Creado'), ('ticket_asignado', 'Ticket Asignado'), ('ticket_nuevo_admin', 'Nuevo Ticket (Admin)'), ('sistema', 'Sistema')], default='general', max_length=50),
        ),
    ]
