# Generated by Django 5.2.7 on 2025-12-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_at_message_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
    ]
