# Generated by Django 5.2.7 on 2025-10-29 14:09

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto')], default='Abierto', max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.CharField(choices=[('Nomina', 'Nómina'), ('Certificados', 'Certificados'), ('Quejas de transporte', 'Quejas de transporte'), ('Cambios de EPPs', 'Cambios de EPPs'), ('Renovacion de TCA', 'Renovación de TCA')], default='Nomina', max_length=50)),
                ('subcategoria', models.CharField(blank=True, choices=[('Pagos', 'Pagos'), ('Descuentos', 'Descuentos'), ('Bonos', 'Bonos'), ('Horas extras', 'Horas extras'), ('Ascensos', 'Ascensos'), ('Justificación por permiso médico', 'Justificación por permiso médico'), ('Retenciones judiciales', 'Retenciones judiciales'), ('Cambio de cuenta bancaria', 'Cambio de cuenta bancaria'), ('Certificado laboral', 'Certificado laboral'), ('Certificado de trabajo', 'Certificado de trabajo'), ('Retrasos/ausencias', 'Retrasos/ausencias'), ('Mal comportamiento', 'Mal comportamiento'), ('Nueva ruta', 'Nueva ruta'), ('Objetos perdidos', 'Objetos perdidos'), ('Solicitud de cambio', 'Solicitud de cambio'), ('Talla incorrecta', 'Talla incorrecta'), ('Equipo defectuoso', 'Equipo defectuoso'), ('Falta de dotación', 'Falta de dotación'), ('Vencimiento', 'Vencimiento'), ('Reposición por pérdida', 'Reposición por pérdida'), ('Daño físico', 'Daño físico')], max_length=60, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_aceptacion', models.DateTimeField(default=tickets.models.default_fecha_limite)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('agente_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('agente_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
