# Generated by Django 5.2.7 on 2025-11-28 14:01

import tickets.models.assignment
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveles_aprobacion', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('tiempo_resolucion_estimado', models.PositiveIntegerField(default=24, help_text='Horas estimadas para resolver')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('pendiente_asignacion', 'Pendiente Asignación'), ('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto')], default='Abierto', max_length=30)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tickets/adjuntos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado_resolucion', models.PositiveIntegerField(default=24, help_text='Horas estimadas para resolver')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating de 1-5', null=True)),
                ('comentario_cierre', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_aceptacion', models.DateTimeField(default=tickets.models.assignment.default_fecha_limite)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historial de tickets',
                'ordering': ['-fecha'],
            },
        ),
    ]
