# Generated by Django 5.2.7 on 2025-11-28 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprincipal',
            name='tipo_agente',
            field=models.ForeignKey(blank=True, help_text='Rol de agente requerido para atender esta categoría', limit_choices_to={'tipo_base__in': ['agente', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rol'),
        ),
        migrations.AddField(
            model_name='flujoaprobacion',
            name='aprobadores',
            field=models.ManyToManyField(limit_choices_to={'rol__nombre_clave__in': ['admin', 'agente']}, related_name='flujos_aprobacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tickets.categoriaprincipal'),
        ),
        migrations.AddField(
            model_name='flujoaprobacion',
            name='subcategoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.subcategoria'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoria_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoriaprincipal'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.subcategoria'),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='agente_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='agente_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_tic_estado_03d285_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['solicitante', 'fecha_creacion'], name='tickets_tic_solicit_0f3846_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['agente', 'estado'], name='tickets_tic_agente__006493_idx'),
        ),
    ]
