# Generated by Django 5.2.7 on 2025-12-02 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprincipal',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría Principal', 'verbose_name_plural': 'Categorías Principales'},
        ),
        migrations.AlterField(
            model_name='categoriaprincipal',
            name='color',
            field=models.CharField(default='#3498db', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriaprincipal',
            name='orden',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='categoriaprincipal',
            name='tipo_agente',
            field=models.ForeignKey(blank=True, help_text='Rol que puede atender tickets de esta categoría (opcional)', limit_choices_to={'tipo_base__in': ['agente', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rol'),
        ),
        migrations.AlterField(
            model_name='flujoaprobacion',
            name='aprobadores',
            field=models.ManyToManyField(limit_choices_to={'rol__tipo_base__in': ['admin', 'agente']}, related_name='flujos_aprobacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
