# Generated by Django 5.2.7 on 2025-12-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
        ('tickets', '0003_alter_categoriaprincipal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_estado_03d285_idx',
        ),
        migrations.AddField(
            model_name='categoriaprincipal',
            name='prioridad_por_defecto',
            field=models.ForeignKey(blank=True, help_text='Prioridad que se asignará automáticamente a los tickets de esta categoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.priority'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='tickets_tic_estado_c74d8e_idx'),
        ),
    ]
