# Generated by Django 4.2.6 on YYYY-MM-DD HH:MM

from django.db import migrations

def populate_ticket_priority(apps, schema_editor):
    """
    Copia los valores de prioridad del campo CharField 'prioridad'
    al nuevo ForeignKey 'prioridad_fk'.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    Priority = apps.get_model('adminpanel', 'Priority')

    # Asegurarse de que las prioridades por defecto existan en la base de datos
    # Si no existen, las creamos. Esto hace la migración más robusta.
    priority_baja, _ = Priority.objects.get_or_create(nombre='Baja', defaults={'nivel': 1, 'color': '#2ecc71'})
    priority_media, _ = Priority.objects.get_or_create(nombre='Media', defaults={'nivel': 2, 'color': '#f39c12'})
    priority_alta, _ = Priority.objects.get_or_create(nombre='Alta', defaults={'nivel': 3, 'color': '#e74c3c'})

    # Mapeo de nombres de prioridad antiguos a objetos Priority
    priority_map = {
        'Baja': priority_baja,
        'Media': priority_media,
        'Alta': priority_alta,
    }

    # Iterar sobre todos los tickets y asignar la prioridad_fk
    for ticket in Ticket.objects.all():
        old_priority_name = ticket.prioridad # Accede al campo CharField existente
        if old_priority_name in priority_map:
            ticket.prioridad_fk = priority_map[old_priority_name]
            ticket.save(update_fields=['prioridad_fk']) # Guardar solo el campo modificado

def reverse_populate_ticket_priority(apps, schema_editor):
    """
    Función para revertir la migración (opcional, pero buena práctica).
    Simplemente limpia el campo prioridad_fk.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        ticket.prioridad_fk = None
        ticket.save(update_fields=['prioridad_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_tickets_tic_estado_03d285_idx_and_more'), # ✅ Dependencia corregida
        ('adminpanel', '0001_initial'), # Asegura que el modelo Priority esté disponible
    ]

    operations = [
        migrations.RunPython(populate_ticket_priority, reverse_populate_ticket_priority),
    ]
