# Generated by Django 5.2.7 on 2025-12-04 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
        ('tickets', '0005_auto_20251204_0945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_estado_c74d8e_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='prioridad',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'prioridad_fk'], name='tickets_tic_estado_4360a2_idx'),
        ),
    ]
