# Generated by Django 5.2.7 on 2025-12-04 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_tickets_tic_estado_c74d8e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_estado_4360a2_idx',
        ),
        migrations.RemoveField(
            model_name='categoriaprincipal',
            name='prioridad_por_defecto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='prioridad_fk',
        ),
        migrations.AddField(
            model_name='categoriaprincipal',
            name='prioridad_automatica',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', help_text='Prioridad que se asignará automáticamente a los tickets de esta categoría.', max_length=20),
        ),
        migrations.AddField(
            model_name='categoriaprincipal',
            name='tiempo_resolucion_horas',
            field=models.PositiveIntegerField(default=24, help_text='Horas estimadas para resolver tickets de esta categoría'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', help_text='Prioridad del ticket', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='tiempo_resolucion_estimado',
            field=models.PositiveIntegerField(default=24, help_text='Horas estimadas para resolver (si es 0, usa el de la categoría)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('pendiente_asignacion', 'Pendiente Asignación'), ('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating de 1-5', null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_tic_estado_03d285_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['categoria_principal', 'estado'], name='tickets_tic_categor_1a6b31_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad', 'estado'], name='tickets_tic_priorid_64086c_idx'),
        ),
    ]
