# Generated by Django 5.2.7 on 2025-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_asignados', models.IntegerField(default=0)),
                ('tickets_resueltos', models.IntegerField(default=0)),
                ('tiempo_promedio_resolucion', models.FloatField(default=0)),
                ('efectividad', models.FloatField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rendimiento del agente',
                'verbose_name_plural': 'Rendimientos de agentes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa', max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('limite_adjuntos_mb', models.IntegerField(default=10)),
                ('mensaje_auto_respuesta', models.TextField(default='Hemos recibido tu ticket. Un agente te responderá pronto.')),
                ('color_primario', models.CharField(default='#1a73e8', max_length=20)),
                ('horario_laboral', models.CharField(default='Lunes a Viernes - 08:00 a 17:00', max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nivel', models.IntegerField(help_text='1 = Alta, 2 = Media, 3 = Baja')),
                ('color', models.CharField(default='#FF0000', help_text='Color hexadecimal para la interfaz', max_length=20)),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tiempo_respuesta_horas', models.IntegerField()),
                ('tiempo_resolucion_horas', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ROLE_CHANGE', 'Cambio de rol'), ('TICKET_REASSIGN', 'Reasignación de ticket'), ('TICKET_CLOSE', 'Cierre de ticket'), ('WARNING', 'Advertencia')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro del sistema',
                'verbose_name_plural': 'Registros del sistema',
                'ordering': ['-fecha'],
            },
        ),
    ]
