# Generated by Django 5.2.7 on 2025-12-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotacionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha en la que se ejecutará el cambio (a las 00:00).')),
                ('ejecutada', models.BooleanField(default=False, help_text='Indica si el sistema ya procesó este cambio.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(help_text='El agente que va a cambiar de rol.', on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_programadas', to=settings.AUTH_USER_MODEL)),
                ('agente_reemplazo', models.ForeignKey(help_text='IMPORTANTE: Usuario que recibirá automáticamente los tickets ABIERTOS del agente saliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Relevo (Hereda Tickets)')),
                ('rol_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rol', verbose_name='Nuevo Rol Asignado')),
            ],
            options={
                'verbose_name': 'Rotación de Personal',
                'verbose_name_plural': 'Rotaciones Programadas',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
